# Data Ingestion Config
source_data:
  data_path: data/data.csv
  data_url: None
  target_column: expenses
  # drop_columns:

load_data:
  raw_data_path: artifacts/raw.csv

split_data:
  train_data_path: artifacts/train.csv
  test_data_path: artifacts/test.csv
  split_ratio: 0.3

# Data Transformation Config
preprocessor_obj_path: artifacts/preprocessor.pkl
schema_path: artifacts/schema.yaml

# Model Training Config
model_path: artifacts/trained_model.pkl

# Model Tuner Config
tune_path: artifacts/tuned_model.pkl